clusterName: &clusterName main

endpoint: https://172.16.70.104:6443
additionalMachineCertSans:
  - 172.16.70.104

clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12

domain: cluster.local

allowSchedulingOnMasters: true
CLUSTER_SUBNET: &CLUSTER_SUBNET 172.16.70.0/24
nodes:
  - hostname: kmaster1
    controlPlane: true
    ipAddress: 172.16.70.104
    installDiskSelector:
      size: "<= 500GB"

  - hostname: kworker2
    ipAddress: 172.16.70.106
    controlPlane: false
    installDiskSelector:
      size: "<= 500GB"

controlPlane:
  # Check https://www.talos.dev/v1.9/talos-guides/network/ingress-firewall/
  # for ingress-firewall details
  ingressFirewall:
    defaultAction: block
    rules:
      - name: kubelet-ingress
        portSelector:
          ports:
            - 10250
          protocol: tcp
        ingress:
          - subnet: *CLUSTER_SUBNET
      - name: apid-ingress
        portSelector:
          ports:
            - 50000
          protocol: tcp
        ingress:
          - subnet: 0.0.0.0/0
          - subnet: ::/0
      - name: trusted-ingress
        portSelector:
          ports:
            - 50001
          protocol: tcp
        ingress:
          - subnet: *CLUSTER_SUBNET
      - name: kubernetes-api-ingress
        portSelector:
          ports:
            - 6443
          protocol: tcp
        ingress:
            - subnet: 0.0.0.0/0
            - subnet: ::/0 
      - name: cni-vxlan
        portSelector:
          ports:
            - 4789 #Flannel
          protocol: udp
        ingress:
          - subnet: *CLUSTER_SUBNET          
      # Should  be the ip ipAddress of the controlPlane nodes
      # - name: etcd-ingress
      #   portSelector:
      #     ports:
      #       - 2379-2380
      #     protocol: tcp
      #   ingress:
      #     - subnet: $CP1/32
      #     - subnet: $CP2/32
      #     - subnet: $CP3/32
worker:
  ingressFirewall:
    defaultAction: block
    rules:
      - name: kubelet-ingress
        portSelector:
          ports:
            - 10250
          protocol: tcp
        ingress:
          - subnet: *CLUSTER_SUBNET
      - name: apid-ingress
        portSelector:
          ports:
            - 50000
          protocol: tcp
        ingress:
          - subnet: 0.0.0.0/0
          - subnet: ::/0
      - name: cni-vxlan
        portSelector:
          ports:
            - 4789 #Flannel
          protocol: udp
        ingress:
          - subnet: *CLUSTER_SUBNET          
